import type { MutableRGBA } from "../animation/keyframes";
import { resolveRenderLayer } from "../render/render-layers";
import { drawRibbon, type RibbonProfile } from "../render/ribbon";
import { type RenderContext, RenderSystem } from "../system";
import { activeStrikes, BOLT_SECONDS } from "./lightning-system";

/**
 * Draws the bolts the scheduler is holding, into the render slot the VFX
 * allocation reserves for lightning (`overlay#2`).
 *
 * A bolt is two passes of the same strand: a wide, dim additive glow and a thin
 * bright core over it. Both are untextured quad chains through `drawRibbon`, so
 * a bolt costs a handful of quads and nothing is sampled or filtered — the
 * `NEAREST`, no-anti-aliasing vocabulary holds by construction.
 *
 * The geometry is regenerated by nobody: it was built once from the strike's
 * seed when the strike was scheduled, and this reads it. The one thing that
 * moves per frame is the fade, so a bolt is a hard-edged shape that dims rather
 * than a shape that wriggles.
 */

const BOLT_LAYER = "overlay";
const BOLT_ORDER = 2;

/** Core width in world units at full intensity. */
const CORE_WIDTH = 3;

/** Glow width in world units at full intensity. */
const GLOW_WIDTH = 14;

/** Peak alpha of the glow pass, before the strike's own intensity. */
const GLOW_ALPHA = 0.28;

/** Pale blue-white, so a bolt is never a flat white cut-out. */
const BOLT_TINT = [0.85, 0.9, 1] as const;

/** Fraction of a bolt's life spent at full brightness before it fades. */
const HOLD = 0.35;

const fade = (age: number): number => {
	const t = Math.min(1, Math.max(0, age / BOLT_SECONDS));
	return t <= HOLD ? 1 : 1 - (t - HOLD) / (1 - HOLD);
};

export class LightningRenderSystem extends RenderSystem {
	private width = 0;
	private alpha = 0;

	private readonly profile: RibbonProfile = {
		width: (t: number): number =>
			this.width * (0.45 + 0.55 * (1 - t)),
		tint: (_t: number, out: MutableRGBA): void => {
			out[0] = BOLT_TINT[0];
			out[1] = BOLT_TINT[1];
			out[2] = BOLT_TINT[2];
			out[3] = this.alpha;
		},
	};

	render({ renderer, ecs }: RenderContext): void {
		const strikes = activeStrikes(ecs);
		if (strikes.length === 0) {
			return;
		}
		const layer = resolveRenderLayer(ecs, BOLT_LAYER, BOLT_ORDER);
		for (const strike of strikes) {
			if (!strike.bolt) {
				continue;
			}
			const brightness = strike.event.intensity * fade(strike.age);
			if (brightness <= 0) {
				continue;
			}
			for (const strand of strike.bolt.strands) {
				const scale = brightness * strand.intensity;
				this.width = GLOW_WIDTH * scale;
				this.alpha = GLOW_ALPHA * scale;
				drawRibbon(renderer, layer, {
					px: strand.x,
					py: strand.y,
					profile: this.profile,
					blend: "additive",
				});
				this.width = CORE_WIDTH * scale;
				this.alpha = scale;
				drawRibbon(renderer, layer, {
					px: strand.x,
					py: strand.y,
					profile: this.profile,
					blend: "additive",
				});
			}
		}
	}
}
